#!/bin/bash

CBLUT=${CBLUT-./cblutgen}
OPS=${OPS-"-m 1 -isxXyY"}
OUT=${OUT-out}
DISPLAY_WIDTH=${DISPLAY_WIDTH-256}

mkdir -p $OUT
pushd $OUT

echo "Results for Protanopia"   > results-protanope.md
echo "Results for Deuteranopia" > results-deuteranope.md
echo "Results for Tritanopia"   > results-tritanope.md

for c in protanope deuteranope tritanope; do
    cat << EOF >> results-$c.md
-------

From left to right: original, Daltonised (Fidaner), corrected (Willmott),
simulated colour blindness, Daltonised + simulated, corrected + simulated.

EOF

done

for i in ../tests/*.*; do
    BASE=${i##*/}
    IMAGE=${BASE%.*}

    echo "=== processing " $IMAGE

    mkdir -p $IMAGE
    pushd $IMAGE

        # Because we modify the originals, which are for red/green colour-blindness,
        # by using -rL for Tritanopia, we must make variant copies of the identity

        ../../$CBLUT -f ../$i -p $OPS
        mv ${IMAGE}_identity.png ${IMAGE}_protanope_identity.png
        ../../$CBLUT -f ../$i -d $OPS
        mv ${IMAGE}_identity.png ${IMAGE}_deuteranope_identity.png
        ../../$CBLUT -f ../$i -t -rL $OPS
        mv ${IMAGE}_identity.png ${IMAGE}_tritanope_identity.png

    popd

    echo "updating results-$c.md"

    for c in protanope deuteranope tritanope; do
        cat << EOF >> results-$c.md
$IMAGE
---

<img src="$IMAGE/${IMAGE}_${c}_identity.png" alt="Original" width="$DISPLAY_WIDTH"/>
<img src="$IMAGE/${IMAGE}_${c}_daltonise.png" alt="Daltonised" width="$DISPLAY_WIDTH"/>
<img src="$IMAGE/${IMAGE}_${c}_correct.png" alt="Corrected" width="$DISPLAY_WIDTH"/>
<img src="$IMAGE/${IMAGE}_${c}_simulate.png" alt="Simulated" width="$DISPLAY_WIDTH"/>
<img src="$IMAGE/${IMAGE}_${c}_simulate_daltonised.png" alt="Simulated Daltonised" width="$DISPLAY_WIDTH"/>
<img src="$IMAGE/${IMAGE}_${c}_simulate_corrected.png" alt="Simulated Corrected" width="$DISPLAY_WIDTH"/>

EOF

    done
done

popd
